### ISSUE TITLE
Design schema to also work with the RiiTag engine

### ISSUE THREAD

**Issue by bennyman123abc** [bennyman123abc/rc24-tag-site#4]
The RiiTag Engine currently uses JSON for user data. This needs to be migrated to some form of SQL. Preferably, we can design a "driver" to use either MySQL or SQLite depending on setup and configuration. This is to be covered by issue #2, however. The only thing needed to solve this issue is a .sql file that can be run on the database to create the required `user` table. If possible, design one for each MySQL and SQLite as mentioned before.

**Comment by larsenv** [comment]
Since we're redoing the site in Python Django, and it has its own DB engine, this issue can be closed.
